services:
  - type: web
    name: documenso
    env: docker
    plan: free
    region: oregon
    branch: main
    # ADD THESE TWO LINES:
    dockerContext: .
    dockerfilePath: ./Dockerfile 
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 3000
      - key: NEXT_PRIVATE_DATABASE_URL
        sync: false
      - key: NEXT_PRIVATE_DIRECT_DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_WEBAPP_URL
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: SMTP_MAIL_HOST
        value: ://gmail.com
      - key: SMTP_MAIL_PORT
        value: 587
      - key: SMTP_MAIL_USER
        sync: false
      - key: SMTP_MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM
        sync: false
